# -*- coding: utf-8 -*-
"""Interacción Con ChatGPT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1479XxUMtsQPUbDPQU0tJfy8JoMLw5pmR

#Estudiante: Simón Rodríguez
##Estos son algunos ejemplos de la interacción que tuve con ChatGPT para ensayar la aplicación.

#Ejemplo 1:
##Pregunta: Genera un texto de tipo informativo sobre el calentamiento global de 2 párrafos.
Respuesta: El calentamiento global es un fenómeno ambiental que se está produciendo en todo el mundo y que tiene graves consecuencias para la humanidad y el planeta. Se trata de un aumento en la temperatura promedio de la Tierra debido a la emisión de gases de efecto invernadero, como el dióxido de carbono, el metano y el óxido de nitrógeno. Estos gases, al retener el calor en la atmósfera, provocan un aumento en la temperatura global y cambios en los patrones climáticos.

El calentamiento global es un problema a largo plazo que requiere la acción urgente de los gobiernos, las empresas y la sociedad en general. La acción humana, como la quema de combustibles fósiles, la deforestación y la intensificación agrícola, es la principal causa de la emisión de gases de efecto invernadero y, por lo tanto, del calentamiento global. Es necesario tomar medidas para reducir las emisiones de gases y proteger el planeta para las generaciones futuras. Esto incluye la transición a fuentes de energía renovable, la implementación de prácticas agrícolas más sostenibles y la conservación de los ecosistemas naturales.

#Ejemplo 2:
##Pregunta: Dame consejos para aprender Pandas en python
Respuesta: Aquí hay algunos consejos para aprender Pandas en Python:

Comprender los conceptos básicos de Python: Antes de comenzar a trabajar con Pandas, es importante tener un conocimiento sólido de Python, incluyendo estructuras de datos como listas y diccionarios.

Leer la documentación: La documentación de Pandas es un recurso valioso y detallado que proporciona una amplia información sobre cómo usar la biblioteca.

Practicar con ejemplos: La mejor forma de aprender Pandas es practicando con ejemplos. Busca tutoriales y ejercicios en línea para poner en práctica lo que has aprendido.

Usar Jupyter Notebook: Jupyter Notebook es una herramienta popular para la exploración y el análisis de datos que facilita el aprendizaje de Pandas.

Trabajar con datasets reales: Es útil trabajar con datasets reales para aplicar tus conocimientos y fortalecer tus habilidades con Pandas. Puedes encontrar datasets en repositorios en línea como Kaggle o UCI Machine Learning Repository.

Participar en comunidades en línea: Las comunidades en línea, como Stack Overflow y Reddit, son un gran recurso para hacer preguntas y obtener ayuda de otros programadores experimentados.

Seguir tutoriales y cursos en línea: Hay muchos tutoriales y cursos en línea disponibles que pueden ayudarte a aprender Pandas desde cero o profundizar en temas más avanzados.

Recuerda que aprender Pandas requiere práctica y paciencia, pero con el tiempo y la dedicación, puedes desarrollar habilidades sólidas en este marco de trabajo de análisis de datos.

#Ejemplo 3:
##Pregunta: Genera un dataset para usar con pandas que tenga la siguiente información: Nombre, Cédula, Fecha de nacimiento, estado civil.
Respuesta: Nombre, Cédula, Fecha de nacimiento, Estado civil
Juan Pérez, 123456789, 01/01/1980, Casado
María Rodriguez, 987654321, 05/03/1985, Soltero
Andrés García, 111111111, 09/07/1990, Casado
Sofía Martínez, 222222222, 02/12/1995, Soltero
Pedro Sánchez, 333333333, 06/06/2000, Casado

#Ejemplo 4:
##Pregunta:Cambia el formato del anterior dataset y conviértelo a formato JSON
"""

Respuesta = [  {    "Nombre": "Juan Pérez",    "Cédula": "123456789",    "Fecha de nacimiento": "01/01/1980",    "Estado civil": "Casado"  }, 
             {    "Nombre": "María Rodriguez",    "Cédula": "987654321",    "Fecha de nacimiento": "05/03/1985",    "Estado civil": "Soltero"  }, 
             {    "Nombre": "Andrés García",    "Cédula": "111111111",    "Fecha de nacimiento": "09/07/1990",    "Estado civil": "Casado"  },  
             {    "Nombre": "Sofía Martínez",    "Cédula": "222222222",    "Fecha de nacimiento": "02/12/1995",    "Estado civil": "Soltero"  },
             {    "Nombre": "Pedro Sánchez",    "Cédula": "333333333",    "Fecha de nacimiento": "06/06/2000",    "Estado civil": "Casado"  }]